// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: DailyMessage.proto

package DailyMessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Date struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date        *string                `protobuf:"bytes,1,opt,name=date"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_DailyMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_DailyMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Date) GetDate() string {
	if x != nil {
		if x.xxx_hidden_Date != nil {
			return *x.xxx_hidden_Date
		}
		return ""
	}
	return ""
}

func (x *Date) SetDate(v string) {
	x.xxx_hidden_Date = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Date) HasDate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Date) ClearDate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Date = nil
}

type Date_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Date *string
}

func (b0 Date_builder) Build() *Date {
	m0 := &Date{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Date != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Date = b.Date
	}
	return m0
}

type DailyMessage struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DailyMessage *string                `protobuf:"bytes,1,opt,name=daily_message,json=dailyMessage"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DailyMessage) Reset() {
	*x = DailyMessage{}
	mi := &file_DailyMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyMessage) ProtoMessage() {}

func (x *DailyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_DailyMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DailyMessage) GetDailyMessage() string {
	if x != nil {
		if x.xxx_hidden_DailyMessage != nil {
			return *x.xxx_hidden_DailyMessage
		}
		return ""
	}
	return ""
}

func (x *DailyMessage) SetDailyMessage(v string) {
	x.xxx_hidden_DailyMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DailyMessage) HasDailyMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DailyMessage) ClearDailyMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DailyMessage = nil
}

type DailyMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DailyMessage *string
}

func (b0 DailyMessage_builder) Build() *DailyMessage {
	m0 := &DailyMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DailyMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_DailyMessage = b.DailyMessage
	}
	return m0
}

var File_DailyMessage_proto protoreflect.FileDescriptor

const file_DailyMessage_proto_rawDesc = "" +
	"\n" +
	"\x12DailyMessage.proto\"\x1a\n" +
	"\x04Date\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"3\n" +
	"\fDailyMessage\x12#\n" +
	"\rdaily_message\x18\x01 \x01(\tR\fdailyMessage24\n" +
	"\tMessenger\x12'\n" +
	"\x0fGetDailyMessage\x12\x05.Date\x1a\r.DailyMessageB7Z5GitHub/aledxandergmiles/proto/Announcer/DailyMessagesb\beditionsp\xe9\a"

var file_DailyMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DailyMessage_proto_goTypes = []any{
	(*Date)(nil),         // 0: Date
	(*DailyMessage)(nil), // 1: DailyMessage
}
var file_DailyMessage_proto_depIdxs = []int32{
	0, // 0: Messenger.GetDailyMessage:input_type -> Date
	1, // 1: Messenger.GetDailyMessage:output_type -> DailyMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DailyMessage_proto_init() }
func file_DailyMessage_proto_init() {
	if File_DailyMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DailyMessage_proto_rawDesc), len(file_DailyMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DailyMessage_proto_goTypes,
		DependencyIndexes: file_DailyMessage_proto_depIdxs,
		MessageInfos:      file_DailyMessage_proto_msgTypes,
	}.Build()
	File_DailyMessage_proto = out.File
	file_DailyMessage_proto_goTypes = nil
	file_DailyMessage_proto_depIdxs = nil
}
